### ISSUE TITLE
Support Typescript instead of plain Javascript

### ISSUE THREAD

**Issue by grajesh690** [bhadmus/postwright#7]
Since playwright is most used along with typescript, it would be great if the conversion is done in Typescript

**Comment by bhadmus** [comment]
The package has been updated with a working typescript version in [1.0.2](https://www.npmjs.com/package/postwright). Read the readme and let me know if it works.

**Comment by bhadmus** [comment]
The package has been updated with a working typescript version in [1.0.2](https://www.npmjs.com/package/postwright). Read the readme and let me know if it works.

> Since playwright is most used along with typescript, it would be great if the conversion is done in Typescript

**Comment by bhadmus** [comment]
This has been implemented and tested @grajesh690 so I will close this issue
